# -*- coding: utf-8 -*-
"""FinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5pgYFxuUwxiOg7D3zlqYixvA5FNf66K
"""
import cv2
import os
from utils.opticalFlow import getMaskFromOpticalFlow, PointsOpticalFlow
from utils.yolo import TrackingByYolo, Yolo

if __name__ == "__main__":
    """# import images"""

    frames = []
    cap = cv2.VideoCapture('re-id/videos/vtest.avi')
    ret, frame = cap.read()
    index = 0
    while ret:
        frames.append(frame)
        ret, frame = cap.read()

    # path = "re-id/sequenses/multi_shot/cam_a/person_0001"
    # f = []
    # for (dirpath, dirnames, filenames) in os.walk(path):
    #     f.extend(filenames)
    #     break
    #
    # f.sort()
    # f = list(map(lambda file: path + "/" + file, f))
    # #getMaskFromOpticalFlow(f,isVideo=False)

    ## init yolo

    yolo = Yolo()
    yolo.initYolo()

    TrackingByYolo(frames, yolo, isVideo=True)
