# -*- coding: utf-8 -*-
"""FinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5pgYFxuUwxiOg7D3zlqYixvA5FNf66K
"""
import cv2
import os
from utils.opticalFlow import getMaskFromOpticalFlow
if __name__ == "__main__":
    """# import images"""

    for i in range(1,30):
        path = "re-id/sequenses/multi_shot/cam_a/person_000"+str(i)
        f = []
        for (dirpath, dirnames, filenames) in os.walk(path):
            f.extend(filenames)
            break

        f.sort()
        f = list(map(lambda file: path + "/" + file, f))

        getMaskFromOpticalFlow(f)
