# -*- coding: utf-8 -*-
"""FinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5pgYFxuUwxiOg7D3zlqYixvA5FNf66K
"""
import cv2
import pprint
import os
from finalProject.classes.enumTypeKeyPoints import NamesAlgorithms
from finalProject.classes.yolo import Yolo
from finalProject.utils.drawing.draw import drawOnScatter, drawFrameObject
from finalProject.utils.keyPoints.AlgoritamKeyPoints import createDescriptorTarget
from finalProject.utils.tracking.TrackingByYolo import TrackingByYolo
import matplotlib.pyplot as plt

import json

if __name__ == "__main__":
    """# import images"""

    with open('./config.txt') as file_json:
        config = json.load(file_json)
        frames = []
        if config["isVideo"]:
            cap = cv2.VideoCapture(config["inputVideo"])
            i = 0
            while i < config["skipRateFrameFromBeginning"]:
                ret, frame = cap.read()
                i += 1
            index = 0
            while ret:
                frames.append(frame)
                ret, frame = cap.read()
        else:
            path = config["inputVideo"]
            for (dirpath, dirnames, filenames) in os.walk(path):
                frames.extend(filenames)
                break
            frames.sort()
            frames = list(map(lambda file: path + "/" + file, frames))

        # init yolo

        yolo = Yolo()
        yolo.initYolo()

        # start algorithm

        myTargets = TrackingByYolo(frames, yolo, isVideo=config["isVideo"], config=config)

        descriptorTarget = createDescriptorTarget(myTargets)

        # pp = pprint.PrettyPrinter(indent=4)
        #
        # pp.pprint(descriptorTarget)

        # frameExmaple = descriptorTarget[0][0]

        # drawFrameObject(frameExmaple)
        # pp.pprint(descriptorTarget)
